bucket:
  enable: true
  name: Duże wiadro
  description: Pochłania płyny
  durability: 100
voidfall:
  enable: true
  #A name to which world you should be teleported after fallig to the void to
  worldName: world
  #If Voidout set to true it will delete whole chunk after the teleportation
  doVoidout: false
sit:
  enable: true
  enter: You are now sitting
  leave: You are now standing