name: UberStuff
version: ${project.version}
main: github.niewidzialny84.uberstuff.UberStuff
api-version: 1.13
authors: [Niewidzialny84]
description: for other memes stuff

commands:
  uberstuff:
    permision: uberstuff
    usage: /uberstuff
    permission-message: You are not allowed to use this command.
  sit:
    permission: uberstuff-sit
    usage: /sit
    permission-message: You are not allowed to use this command.
